language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

install:
  - pip install pybuilder
  - pip install coveralls
  - pyb install_dependencies
script: "pyb verify analyze && coverage run --source=src/main/python/fysom `which pyb` run_unit_tests"
after_success:
  - coveralls --verbose
